 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  pathvqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage:
            - /gemini/data-1/pvqa/train_vqa.json
            - /gemini/data-1/pvqa/pathvqa_answer_list.json
        val:
          storage:
            - /gemini/data-1/pvqa/val_vqa.json
            - /gemini/data-1/pvqa/pathvqa_answer_list.json
        test:
          storage:
            - /gemini/data-1/pvqa/test_vqa.json
            - /gemini/data-1/pvqa/pathvqa_answer_list.json
      images:
          storage: pvqa/images/
